dataset:
  video_processor: The50saladsActionSegmentationVideoProcessor
  bert_name: bert-base-uncased
  meta_processor: The50saladsActionSegmentationMetaProcessor
  vfeat_dir: /home/irene/Desktop/mag_degree/data/50salads/features
  text_processor: The50saladsActionSegmentationTextProcessor
  gt_path: /home/irene/Desktop/mag_degree/data/50salads/groundTruth
  mapping_path: /home/irene/Desktop/mag_degree/data/50salads/mapping.txt
  aligner: The50saladsActionSegmentationAligner
  train_path: /home/irene/Desktop/mag_degree/data/50salads/splits/train.split1.bundle
  val_path: /home/irene/Desktop/mag_degree/data/50salads/splits/test.split1.bundle
  num_iso_layer: 12
  sliding_window: 8
  sliding_window_size: 32
  max_video_len: 32
  max_len: 96
fairseq:
  common:
    tensorboard_logdir: run
    log_interval: 1000
    fp16: true
  dataset:
    num_workers: 1 # was 4
    batch_size: 1
  optimization:
    lr:
    - 5.0e-05
    clip_norm: 2.0
    optimizer: adam
    adam_betas: (0.9, 0.98)
    lr_scheduler: polynomial_decay
    total_num_update: 1000000
    warmup_updates: 122
    weight_decay: 0.0
    ddp_backend: no_c10d
    max_epoch: 8
  checkpoint:
    restore_file: runs/retri/videoclip/checkpoint_best.pt
    reset_optimizer: true
    reset_dataloader: true
    reset_meters: true
    save_dir: /home/irene/Desktop/mag_degree/50salads_VideoCLIP
task_type: sweep_big
model:
  model_cls: MMFusionSeparateActionSegmentation
  mm_encoder_cls: null
  video_encoder_cls: MMBertForTokenClassification
  text_encoder_cls: BertModel
  num_hidden_video_layers: 6
loss:
  loss_cls: CrossEntropy
