slurm_config: big
task_type: local_predict
dataset:
  split: test
  video_processor: VideoProcessor
  aligner: The50saladsActionSegmentationAligner
  bert_name: bert-base-uncased
  meta_processor: The50saladsActionSegmentationMetaProcessor
  vfeat_dir: /home/irene/Desktop/mag_degree/data/50salads/features
  text_processor: The50saladsActionSegmentationTextProcessor
  gt_path: /home/irene/Desktop/mag_degree/data/50salads/groundTruth
  mapping_path: /home/irene/Desktop/mag_degree/data/50salads/mapping.txt
  num_iso_layer: 12
  sliding_window: 16
  sliding_window_size: 32
  max_video_len: 32
  max_len: 96
fairseq:
  dataset:
    batch_size: 1
    valid_subset: test
    num_workers: 2
  common_eval:
    path: runs/retri/videoclip/checkpoint_best.pt
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 6
eval:
  save_path: /home/irene/Desktop/mag_degree/50salads_VideoCLIP
metric: COINActionSegmentationMetric
predictor: COINZSPredictor
